# Generated by Django 4.2.17 on 2025-01-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the About Page', max_length=200)),
                ('content', models.TextField(help_text='Enter the main content for the About page')),
                ('updated_on', models.DateTimeField(auto_now=True, help_text='The date and time when the page was last updated')),
            ],
        ),
    ]
